version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'

sphinx:
  builder: html
  configuration: ./docs/Sphinx/conf.py
  fail_on_warning: true

# Build PDF & ePub
formats:
  - epub
  - pdf
