m0st4fa::fsm::FiniteStateMachine
friend struct FSMResult
FSMStateSetType m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_FinalStates
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getFinalStates, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::operator=.
FSM_TYPE m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_MachineType
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getMachineType, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::operator=.
FlagsType m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_Flags
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getFlags, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::operator=.
Logger m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_Logger
Used to log to the console in a standard way, implementing the correct colors.
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::FiniteStateMachine.
TransFuncT m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_TransitionFunc
The function that will be called on each transition.
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::operator=.
constexpr FSMStateType m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::START_STATE
The start state that will be used by the state machine.
bool m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::_is_state_final(const FSMStateSetType &state) const
Checks whether state is final (contains at least one final state) and returns a boolean indicating it.
This is often used to check whether a string is accepted or not (whether we've reached an accepting state). state The state set to check for whether it is final or not. True if state is a final state set; False otherwise.
References m0st4fa::fsm::FSMStateSetType::contains, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getFinalStates.
FSMStateSetType m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::_get_final_states_from_state_set(const FSMStateSetType &state) const
Searches for the final states within a state set and returns them.
state The state set that will be searched. The final states within state, if any.
References m0st4fa::fsm::FSMStateSetType::contains, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getFinalStates, m0st4fa::fsm::FSMStateSetType::insert.
m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::FiniteStateMachine()=default
Default constructor.
m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::FiniteStateMachine(const FSMStateSetType &fStates, const TransFuncT &tranFn, FSM_TYPE machineType, FlagsType flags)
The typical constructor that will be used to construct a state machine.
fStates The final states of the state machine. tranFn The transition function of the state machine. machineType The type of the state machine. flags The flags given to the state machine.
References m0st4fa::fsm::FSMStateSetType::empty, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_Logger, m0st4fa::fsm::MT_MACHINE_TYPE_COUNT.
FiniteStateMachine & m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::operator=(const FiniteStateMachine &rhs)
Copy operator for the state machine.
rhs The right hand side (right argument) of the copy operator. A reference to the state machine after assignment.
References m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_FinalStates, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_Flags, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_MachineType, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_TransitionFunc.
Referenced by m0st4fa::fsm::DeterFiniteAutomaton< TransFuncT, InputT >::operator=.
const FSMStateSetType & m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getFinalStates() const
Gets the final states of the state machine.
References m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_FinalStates.
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::_get_final_states_from_state_set, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::_is_state_final.
FlagsType m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getFlags() const
Gets the flags of the state machine.
References m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_Flags.
FSM_TYPE m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::getMachineType() const
Gets the type of the state machine. For a DFA, the type is always FSM_TYPE::MT_DFA; for an NFA it varies.
References m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::m_MachineType.