m0st4fa::fsm::FSMStateSetType
using m0st4fa::fsm::FSMStateSetType::SetType = std::set<FSMStateType>
SetType m0st4fa::fsm::FSMStateSetType::m_StateSet
Referenced by begin, begin, contains, empty, end, end, insert, insert, insert, operator SetType, operator=, size.
m0st4fa::fsm::FSMStateSetType::FSMStateSetType(const std::initializer_list< FSMStateType > &i)
m0st4fa::fsm::FSMStateSetType::FSMStateSetType(const SetType &set)
m0st4fa::fsm::FSMStateSetType::FSMStateSetType(const FSMStateType state)
m0st4fa::fsm::FSMStateSetType::FSMStateSetType()=default
m0st4fa::fsm::FSMStateSetType::operator SetType() const
References m_StateSet.
m0st4fa::fsm::FSMStateSetType::operator FSMStateType() const
References begin, empty.
void m0st4fa::fsm::FSMStateSetType::insert(const InputIt begin, const InputIt end)
References begin, end, m_StateSet.
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::_get_final_states_from_state_set, m0st4fa::fsm::TransitionFunction< TableT >::operator().
void m0st4fa::fsm::FSMStateSetType::insert(std::initializer_list< FSMStateType > ilist)
References m_StateSet.
void m0st4fa::fsm::FSMStateSetType::insert(const FSMStateType state)
References m_StateSet.
FSMStateSetType & m0st4fa::fsm::FSMStateSetType::operator=(const FSMStateSetType &rhs)
References m_StateSet.
SetType::iterator m0st4fa::fsm::FSMStateSetType::begin()
References m_StateSet.
Referenced by m0st4fa::fsm::NonDeterFiniteAutomaton< TransFuncT, InputT >::_epsilon_closure, insert, operator FSMStateType, m0st4fa::fsm::TransitionFunction< TableT >::operator(), m0st4fa::fsm::operator<<.
SetType::iterator m0st4fa::fsm::FSMStateSetType::end()
References m_StateSet.
Referenced by m0st4fa::fsm::NonDeterFiniteAutomaton< TransFuncT, InputT >::_epsilon_closure, insert, m0st4fa::fsm::TransitionFunction< TableT >::operator().
SetType::iterator m0st4fa::fsm::FSMStateSetType::begin() const
References m_StateSet.
SetType::iterator m0st4fa::fsm::FSMStateSetType::end() const
References m_StateSet.
bool m0st4fa::fsm::FSMStateSetType::contains(const FSMStateType val) const
References m_StateSet.
Referenced by m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::_get_final_states_from_state_set, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::_is_state_final.
size_t m0st4fa::fsm::FSMStateSetType::size() const
References m_StateSet.
Referenced by m0st4fa::fsm::NonDeterFiniteAutomaton< TransFuncT, InputT >::_simulate_whole_string.
bool m0st4fa::fsm::FSMStateSetType::empty() const
References m_StateSet.
Referenced by m0st4fa::fsm::NonDeterFiniteAutomaton< TransFuncT, InputT >::_epsilon_closure, m0st4fa::fsm::NonDeterFiniteAutomaton< TransFuncT, InputT >::_simulate_whole_string, m0st4fa::fsm::FiniteStateMachine< TransFuncT, InputT >::FiniteStateMachine, operator FSMStateType.